### ISSUE TITLE
Make this project into package?

### ISSUE THREAD

**Issue by TheCDC** [aroberge/mod_pydoc#2]
Hi! I was googling around for a python documentation generator tool that was easier to set up than sphinx and found pydoc and hated it's theming and then found this! I apologize if this project is kinda dead now but it looks promising. Anyway, I was wondering if it might be a good idea to turn this into a proper Python package with a `setup.py` and all that.

**Comment by aroberge** [comment]
I created this project initially because I too did not like the default theming for pydoc.  I then found out that a bug had been filed for it (http://bugs.python.org/issue10716#msg234936) and modified this project so that it could be a fix for that bug.

Unfortunately, it was not considered, and I essentially abandoned it at that point.
